### ISSUE TITLE
Open empty screen

### ISSUE THREAD

**Issue by Anandhakumar-Pa** [pgorzelany/PGSideMenu#1]
Hi, 
How to disable left menu because i want only right menu.
I tried without adding left menu that time its showing an empty screen.
![img_0520](https://user-images.githubusercontent.com/927067/28104993-5d3952f4-66e6-11e7-9148-9cd311287dd4.PNG)

**Comment by pgorzelany** [comment]
@SOi-bnAnA You are responsible for making the calls to toggle the menu. If you don't want to open the left menu just don't add the button to show the left menu or do not invoke the left menu toggle anywhere is you code.
