### ISSUE TITLE
Need support with Swift 4

### ISSUE THREAD

**Issue by isunilapps** [pgorzelany/PGSideMenu#5]
Now we are using Xcode latest stable version and this pod showing some warnings to unlock

**Comment by pgorzelany** [comment]
@isunilapps is it only warnings or build errors?

**Comment by pvn** [comment]
**Error**: Argument of '#selector' refers to instance method 'overlayTouched' that is not exposed to Objective-C

Add '@objc' to expose this instance method to Objective-C

**Comment by pgorzelany** [comment]
Ok, I will fix that soon

**Comment by pgorzelany** [comment]
Fixed in 1.2.0
